export { default as HomeHero } from './hero'
export { default as HomePopularCourse } from './mission'
export { default as HomeTestimonial } from './services'
export { default as HomeOurMentors } from './benifits'
export { default as HomeContact } from './contact'
