export { default as HomeHero } from './hero'
export { default as HomePopularCourse } from './popular-courses'
export { default as HomeFeature } from './feature'
export { default as HomeTestimonial } from './services'
export { default as HomeOurMentors } from './benifits'
export { default as HomeNewsLetter } from './contact'
