import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/mission/1.jpg',
    title: 'Android Development from Zeo to Hero',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/mission/2.jpg',
    title: 'UI/UX Complete Guide',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/mission/3.jpg',
    title: 'Mastering Data Modeling Fundamentals',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/mission/4.jpg',
    title: 'The Complete Guide Docker and Kubernetes',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/mission/5.jpg',
    title: 'Modern React with MUI & Redux',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/mission/6.jpg',
    title: 'Ethical Hacking Bootcamp Zero to Mastery',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/mission/7',
    title: 'Adobe Lightroom For Beginners: Complete Photo Editing',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
  },
]
